# Generated by Django 4.2.3 on 2023-07-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='pics')),
                ('descp', models.TextField()),
            ],
        ),
    ]
